# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pick2Heal Labs
email: contact@pick2heal.com
slogan: Blood tests at your doorstep
masthead: Care for your family.
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://pick2heal.com' # the base hostname & protocol for your site

address: 'M2, Gayathri, Technopark Campus, Trivandrum, 695581'
phone: '18002586393'

# Build settings
maRkdown: kramdown
permalink: :title

exclude:
    [
        '.git',
        '.svn',
        '.bundle',
        'vendor',
        'assets/semantic',
        'node_modules',
        'gulpfile.js',
        'semantic.json',
        'package.json',
        'README.md',
        'assets/raw',
        'Gemfile',
        'Gemfile.lock',
        '.gulp-scss-cache',
        'assets/css/lightbox.min.css',
        'assets/css/semantic.css',
        'assets/css/semantic.min.css',
        'assets/js/isotope.pkgd.js',
        'assets/js/jquery.min.js',
        'assets/js/lightbox.min.js',
        'assets/js/lightbox.min.map',
        'assets/js/semantic.js',
    ]

encoding: 'utf-8'
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'

plugins:
    - jekyll-gist
    - jekyll-paginate
    - jekyll-sitemap

paginate: 8
paginate_path: '/blogs/page:num/'
tag_page_dir: tag
tag_feed_dir: tag
tag_page_layout: tag_page
tag_feed_layout: tag_feed

social: ['https://www.facebook.com/pick2heal']

compress_html:
    clippings: [div, p, ul, td, h1, h2]
    comments: ['<!-- ', ' -->']
    endings: []
    ignore:
        envs: [local]
    blanklines: true
    profile: false
    startings: []

sass:
    sass_dir: assets/css
    style: compressed

whitelist:
    - jekyll-gist
    - jekyll-paginate
